Traceback (most recent call last):
  File "/scratch/users/eozlu21/sabanci-competition/main.py", line 174, in <module>
    solve_and_save_results(i)
  File "/scratch/users/eozlu21/sabanci-competition/main.py", line 164, in solve_and_save_results
    _solve_and_save_results_part_two(instance_index)
  File "/scratch/users/eozlu21/sabanci-competition/main.py", line 138, in _solve_and_save_results_part_two
    model = build_part_two_model(instance)
  File "/scratch/users/eozlu21/sabanci-competition/model_part_two.py", line 15, in build_part_two_model
    Y = {
  File "/scratch/users/eozlu21/sabanci-competition/model_part_two.py", line 16, in <dictcomp>
    (i, j): 1 if j in instance.assignments[i][1] else 0
KeyError: 633
